from cli.agent_cli import app_server_protocol_flow_helpers_runtime
from cli.agent_cli import app_server_protocol_turn_flow_runtime


def test_app_server_protocol_flow_helpers_reexports_turn_flow_helpers() -> None:
    assert app_server_protocol_flow_helpers_runtime.run_turn_start_job is app_server_protocol_turn_flow_runtime.run_turn_start_job
    assert app_server_protocol_flow_helpers_runtime.start_turn_start_job is app_server_protocol_turn_flow_runtime.start_turn_start_job
    assert app_server_protocol_flow_helpers_runtime.handle_turn_start is app_server_protocol_turn_flow_runtime.handle_turn_start
