from __future__ import annotations

import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from cli.agent_cli.runtime_kernels.codex_sidecar.config_projection_models import (
    CODEX_HOME_ENV,
    DEFAULT_PROJECTED_CODEX_HOME_DIR,
    DEFAULT_SCRUBBED_AUTH_ENV_KEYS,
    CodexSidecarProjectedConfig,
)


def _projected_codex_home(provider_home: str | Path) -> Path:
    return (Path(provider_home).expanduser() / DEFAULT_PROJECTED_CODEX_HOME_DIR).resolve(
        strict=False
    )


def _prepare_isolated_projected_config(
    *,
    codex_home: Path,
    config_path: Path,
) -> CodexSidecarProjectedConfig | None:
    auth_path = codex_home / "auth.json"
    try:
        config_path.parent.mkdir(parents=True, exist_ok=True)
        _write_text_if_changed(
            config_path,
            "# Generated by AgentHub. Do not edit by hand.\n"
            "# No AgentHub Codex provider is configured yet.\n",
        )
        _remove_file_if_exists(auth_path)
    except OSError:
        return None
    return CodexSidecarProjectedConfig(
        codex_home=codex_home,
        config_path=config_path,
        env={CODEX_HOME_ENV: str(codex_home)},
        scrubbed_env_keys=DEFAULT_SCRUBBED_AUTH_ENV_KEYS,
        generated=True,
    )


def _write_text_if_changed(path: Path, text: str) -> None:
    try:
        if path.exists() and path.read_text(encoding="utf-8") == text:
            return
    except OSError:
        pass
    path.write_text(text, encoding="utf-8")


def _write_json_secret_if_changed(path: Path, payload: Mapping[str, Any]) -> None:
    rendered = json.dumps(dict(payload), ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    try:
        if path.exists() and path.read_text(encoding="utf-8") == rendered:
            _chmod_private(path)
            return
    except OSError:
        pass
    path.write_text(rendered, encoding="utf-8")
    _chmod_private(path)


def _remove_file_if_exists(path: Path) -> None:
    try:
        path.unlink()
    except FileNotFoundError:
        return


def _chmod_private(path: Path) -> None:
    try:
        path.chmod(0o600)
    except OSError:
        pass
