from __future__ import annotations

import re
from collections.abc import Mapping
from typing import Any

from cli.agent_cli.provider_catalog_toml_runtime import quoted_toml_string


def render_codex_config_toml(projection: Mapping[str, Any]) -> str:
    model = str(projection.get("model") or "").strip()
    model_provider = str(projection.get("model_provider") or "").strip()
    provider = projection.get("provider")
    provider_block = dict(provider) if isinstance(provider, Mapping) else {}
    lines = [
        "# Generated by AgentHub. Do not edit by hand.",
        "# Edit AgentHub provider config instead.",
        f"model = {_toml_string(model)}",
        f"model_provider = {_toml_string(model_provider)}",
        "",
        f"[model_providers.{model_provider}]",
    ]
    for key in (
        "name",
        "base_url",
        "wire_api",
        "requires_openai_auth",
        "experimental_bearer_token",
        "request_max_retries",
        "stream_max_retries",
        "stream_idle_timeout_ms",
        "websocket_connect_timeout_ms",
        "supports_websockets",
    ):
        if key not in provider_block:
            continue
        lines.append(_toml_key_value(key, provider_block[key]))
    for nested_key in ("query_params", "http_headers", "env_http_headers"):
        value = provider_block.get(nested_key)
        if isinstance(value, Mapping) and value:
            lines.append(f"{nested_key} = {_toml_inline_table(value)}")
    return "\n".join(lines).rstrip() + "\n"


def _toml_key_value(key: str, value: Any) -> str:
    if isinstance(value, bool):
        return f"{key} = {'true' if value else 'false'}"
    if isinstance(value, int):
        return f"{key} = {value}"
    if isinstance(value, float):
        return f"{key} = {value}"
    return f"{key} = {_toml_string(str(value))}"


def _toml_inline_table(value: Mapping[str, Any]) -> str:
    items = []
    for key, raw_value in value.items():
        normalized_key = str(key or "").strip()
        if not normalized_key:
            continue
        items.append(f"{_toml_bare_or_quoted_key(normalized_key)} = {_toml_scalar(raw_value)}")
    return "{ " + ", ".join(items) + " }"


def _toml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return str(value)
    return _toml_string(str(value))


def _toml_bare_or_quoted_key(key: str) -> str:
    return key if re.fullmatch(r"[A-Za-z0-9_-]+", key) else _toml_string(key)


def _toml_string(value: str) -> str:
    return quoted_toml_string(str(value))
