from __future__ import annotations

from cli.agent_cli.acceptance_support import (
    web_search_wave02_support_projection_helpers as web_search_wave02_support_projection_helpers_service,
)
from cli.agent_cli.acceptance_support import (
    web_search_wave02_support_pure_helpers as web_search_wave02_support_pure_helpers_service,
)
from cli.agent_cli.acceptance_support import (
    web_search_wave02_support_runtime_helpers as web_search_wave02_support_runtime_helpers_service,
)


DEFAULT_AGENTHUB_MAIN = web_search_wave02_support_pure_helpers_service.DEFAULT_AGENTHUB_MAIN
DEFAULT_PROVIDER_HOME = web_search_wave02_support_pure_helpers_service.DEFAULT_PROVIDER_HOME
DEFAULT_REPORT_ROOT = web_search_wave02_support_pure_helpers_service.DEFAULT_REPORT_ROOT
DEFAULT_CODEX_HOME = web_search_wave02_support_pure_helpers_service.DEFAULT_CODEX_HOME
DEFAULT_CLAUDE_BIN = web_search_wave02_support_pure_helpers_service.DEFAULT_CLAUDE_BIN

AGENTHUB_OPENAI_NATIVE_BACKEND = web_search_wave02_support_pure_helpers_service.AGENTHUB_OPENAI_NATIVE_BACKEND
AGENTHUB_ANTHROPIC_NATIVE_BACKEND = web_search_wave02_support_pure_helpers_service.AGENTHUB_ANTHROPIC_NATIVE_BACKEND
AGENTHUB_LOCAL_BACKEND = web_search_wave02_support_pure_helpers_service.AGENTHUB_LOCAL_BACKEND
CLAUDE_WEB_SEARCH_SCHEMA = web_search_wave02_support_pure_helpers_service.CLAUDE_WEB_SEARCH_SCHEMA

PromptFamily = web_search_wave02_support_pure_helpers_service.PromptFamily
PROMPT_FAMILIES = web_search_wave02_support_pure_helpers_service.PROMPT_FAMILIES
CommandResult = web_search_wave02_support_pure_helpers_service.CommandResult

_iso_now = web_search_wave02_support_pure_helpers_service._iso_now
_selected_cases = web_search_wave02_support_pure_helpers_service._selected_cases
_clean_strings = web_search_wave02_support_pure_helpers_service._clean_strings
_to_int = web_search_wave02_support_pure_helpers_service._to_int
_action_rows = web_search_wave02_support_pure_helpers_service._action_rows
_response_completed_truth = web_search_wave02_support_pure_helpers_service._response_completed_truth
_effective_web_search_mode_for_turn = (
    web_search_wave02_support_pure_helpers_service._effective_web_search_mode_for_turn
)
_external_web_access_for_turn = web_search_wave02_support_pure_helpers_service._external_web_access_for_turn
_tool_surface_contract = web_search_wave02_support_pure_helpers_service._tool_surface_contract
_default_openai_base_url = web_search_wave02_support_pure_helpers_service._default_openai_base_url
_answer_quality = web_search_wave02_support_pure_helpers_service._answer_quality
_case_request_contract_deltas = web_search_wave02_support_pure_helpers_service._case_request_contract_deltas

_write_text = web_search_wave02_support_runtime_helpers_service._write_text
_write_json = web_search_wave02_support_runtime_helpers_service._write_json
_read_json = web_search_wave02_support_runtime_helpers_service._read_json
_run_command = web_search_wave02_support_runtime_helpers_service._run_command
_skipped_command = web_search_wave02_support_runtime_helpers_service._skipped_command
_agenthub_detail = web_search_wave02_support_runtime_helpers_service._agenthub_detail
_codex_detail = web_search_wave02_support_runtime_helpers_service._codex_detail
_claude_detail = web_search_wave02_support_runtime_helpers_service._claude_detail

_agenthub_parity_evidence = web_search_wave02_support_projection_helpers_service._agenthub_parity_evidence
_codex_parity_evidence = web_search_wave02_support_projection_helpers_service._codex_parity_evidence
_claude_parity_evidence = web_search_wave02_support_projection_helpers_service._claude_parity_evidence
_parity_evidence = web_search_wave02_support_projection_helpers_service._parity_evidence
_observable_execution_path = web_search_wave02_support_projection_helpers_service._observable_execution_path
_request_contract = web_search_wave02_support_projection_helpers_service._request_contract
_outcome_classification = web_search_wave02_support_projection_helpers_service._outcome_classification
_supported_conclusions = web_search_wave02_support_projection_helpers_service._supported_conclusions
_unsupported_conclusions = web_search_wave02_support_projection_helpers_service._unsupported_conclusions
_provider_instability_notes = web_search_wave02_support_projection_helpers_service._provider_instability_notes
_case_report = web_search_wave02_support_projection_helpers_service._case_report
_markdown_report = web_search_wave02_support_projection_helpers_service._markdown_report
build_case_system_summary = web_search_wave02_support_projection_helpers_service.build_case_system_summary
