from __future__ import annotations

from typing import Any


def copy_list(values: list[str] | tuple[str, ...] | None = None) -> list[str]:
    return [str(item).strip() for item in (values or []) if str(item).strip()]


def copy_map(value: dict[str, Any] | None = None) -> dict[str, Any]:
    return dict(value or {})


def default_method_payloads() -> list[dict[str, Any]]:
    return [
        {
            "method": "connect.initialize",
            "family": "connect",
            "description": "Initialize a gateway session and return protocol bootstrap details.",
            "auth_required": False,
            "required_scopes": [],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
        {
            "method": "connect.capabilities",
            "family": "connect",
            "description": "Return gateway method and capability metadata for the connected client.",
            "auth_required": False,
            "required_scopes": [],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
        {
            "method": "connect.ping",
            "family": "connect",
            "description": "Round-trip ping for gateway transports and control-plane health checks.",
            "auth_required": False,
            "required_scopes": [],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
        {
            "method": "access.posture.get",
            "family": "access",
            "description": "Return access/auth posture plus pairing pending summary for Control UI.",
            "auth_required": False,
            "required_scopes": [],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
        {
            "method": "nodes.list",
            "family": "nodes",
            "description": "Return first-phase nodes/devices inventory derived from runtime, gateway state, and access posture.",
            "auth_required": True,
            "required_scopes": ["gateway.read"],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
        {
            "method": "config.validate",
            "family": "config",
            "description": "Validate a control-plane config draft and return machine-readable apply/restart posture.",
            "auth_required": False,
            "required_scopes": [],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
        {
            "method": "config.apply",
            "family": "config",
            "description": "Apply a validated control-plane config subset and return post-apply state plus restart posture.",
            "auth_required": False,
            "required_scopes": [],
            "control_plane_write": True,
            "emits_events": True,
            "idempotent": False,
        },
        {
            "method": "config.restart.report",
            "family": "config",
            "description": "Report restart impact for a config draft without performing a restart.",
            "auth_required": False,
            "required_scopes": [],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
        {
            "method": "health.get",
            "family": "health",
            "description": "Gateway health and readiness summary.",
            "auth_required": True,
            "required_scopes": ["gateway.read"],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
        {
            "method": "health.probes",
            "family": "health",
            "description": "Detailed readiness probes for runtime, plugins, and browser control.",
            "auth_required": True,
            "required_scopes": ["gateway.read"],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
        {
            "method": "gateway.state.get",
            "family": "gateway_state",
            "description": "Query approvals, workflows, audits, and events.",
            "auth_required": True,
            "required_scopes": ["gateway.read"],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
        {
            "method": "gateway.events.list",
            "family": "gateway_state",
            "description": "List persisted gateway ingress events.",
            "auth_required": True,
            "required_scopes": ["gateway.read"],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
        {
            "method": "gateway.workflows.list",
            "family": "gateway_state",
            "description": "List persisted workflow runs from the gateway state store.",
            "auth_required": True,
            "required_scopes": ["gateway.read"],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
        {
            "method": "gateway.trace.timeline",
            "family": "gateway_state",
            "description": "Return a trace-oriented timeline across workflow, approval, and audit records.",
            "auth_required": True,
            "required_scopes": ["gateway.read"],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
        {
            "method": "approvals.list",
            "family": "approvals",
            "description": "List pending or historical approval tickets.",
            "auth_required": True,
            "required_scopes": ["approvals.read"],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
        {
            "method": "approvals.get",
            "family": "approvals",
            "description": "Return one approval ticket together with causality context.",
            "auth_required": True,
            "required_scopes": ["approvals.read"],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
        {
            "method": "approvals.resolve",
            "family": "approvals",
            "description": "Approve or reject a pending controlled action.",
            "auth_required": True,
            "required_scopes": ["approvals.resolve"],
            "control_plane_write": True,
            "emits_events": True,
            "idempotent": False,
        },
        {
            "method": "browser.proxy",
            "family": "browser",
            "description": "Proxy raw browser commands through the gateway surface.",
            "auth_required": True,
            "required_scopes": ["browser.write"],
            "control_plane_write": True,
            "emits_events": True,
            "idempotent": False,
            "metadata": copy_map({"transport": "proxy"}),
        },
        {
            "method": "browser.workflow.run",
            "family": "browser",
            "description": "Start a gateway-owned browser workflow execution.",
            "auth_required": True,
            "required_scopes": ["browser.write"],
            "control_plane_write": True,
            "emits_events": True,
            "idempotent": False,
        },
        {
            "method": "browser.playbook.run",
            "family": "browser",
            "description": "Start a named browser playbook under gateway supervision.",
            "auth_required": True,
            "required_scopes": ["browser.write"],
            "control_plane_write": True,
            "emits_events": True,
            "idempotent": False,
        },
        {
            "method": "github.webhook.ingest",
            "family": "github",
            "description": "Ingest a GitHub webhook into the gateway event pipeline.",
            "auth_required": True,
            "required_scopes": ["github.read"],
            "control_plane_write": False,
            "emits_events": True,
            "idempotent": False,
        },
        {
            "method": "github.actions.dispatch",
            "family": "github",
            "description": "Create an approval-gated GitHub workflow dispatch action request.",
            "auth_required": True,
            "required_scopes": ["github.write"],
            "control_plane_write": True,
            "emits_events": True,
            "idempotent": False,
        },
        {
            "method": "github.issues.create",
            "family": "github",
            "description": "Create an approval-gated GitHub issue action request.",
            "auth_required": True,
            "required_scopes": ["github.write"],
            "control_plane_write": True,
            "emits_events": True,
            "idempotent": False,
        },
        {
            "method": "github.comments.create",
            "family": "github",
            "description": "Create an approval-gated GitHub issue comment action request.",
            "auth_required": True,
            "required_scopes": ["github.write"],
            "control_plane_write": True,
            "emits_events": True,
            "idempotent": False,
        },
        {
            "method": "plugins.list",
            "family": "plugins",
            "description": "List gateway-visible plugins and their control-plane state.",
            "auth_required": True,
            "required_scopes": ["plugins.read"],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
        {
            "method": "plugins.connectors.list",
            "family": "plugins",
            "description": "List connector registrations exposed by loaded plugins.",
            "auth_required": True,
            "required_scopes": ["plugins.read"],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
        {
            "method": "plugins.triggers.list",
            "family": "plugins",
            "description": "List trigger registrations exposed by loaded plugins.",
            "auth_required": True,
            "required_scopes": ["plugins.read"],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
        {
            "method": "workflows.list",
            "family": "workflows",
            "description": "List gateway workflow runs visible to operators.",
            "auth_required": True,
            "required_scopes": ["gateway.read"],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
        {
            "method": "workflows.get",
            "family": "workflows",
            "description": "Return one workflow run with operator diagnostics context.",
            "auth_required": True,
            "required_scopes": ["gateway.read"],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
        {
            "method": "workflows.resume",
            "family": "workflows",
            "description": "Resume a paused gateway workflow execution.",
            "auth_required": True,
            "required_scopes": ["gateway.write"],
            "control_plane_write": True,
            "emits_events": True,
            "idempotent": False,
        },
        {
            "method": "logs.tail",
            "family": "logs",
            "description": "Read a bounded tail slice from gateway-visible logs.",
            "auth_required": True,
            "required_scopes": ["gateway.read"],
            "control_plane_write": False,
            "emits_events": False,
            "idempotent": True,
        },
    ]
