from __future__ import annotations

from cli.agent_cli import provider as _provider


_REEXPORT_NAMES = (
    "APP_DIR",
    "LOCAL_CONFIG_DIRNAME",
    "LEGACY_LOCAL_CONFIG_DIRNAME",
    "LOCAL_CONFIG_DIR_CANDIDATES",
    "AGENT_CLI_HOME",
    "LEGACY_COMPAT_HOME",
    "AGENT_CLI_CONFIG_TOML",
    "AGENT_CLI_AUTH_JSON",
    "LEGACY_COMPAT_CONFIG_TOML",
    "LEGACY_COMPAT_AUTH_JSON",
    "CLAUDE_SETTINGS_JSON",
    "CLAUDE_CONFIG_JSON",
    "CLAUDE_STATE_JSON",
    "_USER_MODEL_SELECTION_KEYS",
    "PlannerToolExecutor",
    "PluginManagerFactory",
    "ProviderManagementSnapshot",
    "Planner",
    "BasePlanner",
    "ModelCatalogEntry",
    "ProviderCatalog",
    "ProviderConfig",
    "ProviderPathResolution",
    "build_ordered_request_prelude_items",
    "request_prelude_contract",
    "extract_current_turn_prelude_items",
    "extract_current_turn_prelude_contract",
    "load_claude_provider_config",
    "build_planner",
    "save_user_model_selection",
    "_read_json",
    "_read_toml",
    "_quoted_toml_string",
    "_upsert_root_toml_string_key",
    "_read_user_model_selection_toml",
    "_iter_project_roots",
    "_find_project_provider_file",
    "_slugify_model_key",
    "_project_provider_layout",
    "_explicit_provider_home_paths",
    "_related_provider_roots",
    "_discover_provider_project_local_paths",
    "_ensure_project_provider_bootstrap",
    "_home_provider_paths",
    "_project_claude_home_dir",
    "_provider_discovery_feature_settings",
    "_provider_discovery_strict_isolation_enabled",
    "resolve_provider_paths",
    "_build_provider_catalog",
    "_find_model_entry",
    "_default_model_entry",
    "_load_provider_inputs",
    "load_provider_catalog",
    "load_provider_management_snapshot",
    "load_provider_config",
    "_candidate_api_key_names",
    "_first_configured_key",
    "_infer_planner_kind",
    "_quote_arg",
    "_optional_bool",
    "_plugin_system_prompt_addendum",
    "_plugin_tool_call_command",
    "_command_for_tool_call",
    "_tool_result_payload",
    "_looks_like_policy_question",
    "_looks_like_policy_context",
    "_tool_specs",
)

globals().update({name: getattr(_provider, name) for name in _REEXPORT_NAMES})

__all__ = [name for name in _REEXPORT_NAMES if not name.startswith("_")]
