from __future__ import annotations

DISCOVERABLE_SLASH_COMMAND_NAMES: frozenset[str] = frozenset(
    {
        "help",
        "providers",
        "models",
        "setup",
        "provider",
        "model",
        "codex_threads",
        "codex_thread",
        "codex_rollback",
        "codex_compact",
        "status",
        "threads",
        "resume",
        "exit",
        "quit",
        "compact",
        "mcp",
        "init",
        "orchestrate",
        "orchestrate_confirm",
        "orchestrate_dispatch",
        "orchestrate_progress",
        "orchestrate_continue",
        "orchestrate_apply",
        "orchestrate_reject",
        "workflows",
        "background_tasks",
        "runtime_config",
        "lang",
        "theme",
        "tools",
        "plugins",
        "memory",
        "plan",
        "tab_rename",
        "tab_new",
        "approval_inbox",
        "preview",
        "fork",
        "master",
        "fork_child",
        "close",
    }
)


BUSY_MODE_BY_COMMAND: dict[str, str] = {
    "help": "allowed",
    "providers": "allowed",
    "models": "allowed",
    "provider": "read_only",
    "codex_threads": "allowed",
    "codex_thread": "allowed",
    "status": "allowed",
    "setup": "allowed",
    "update": "allowed",
    "runtime_status": "allowed",
    "tools": "allowed",
    "plugins": "allowed",
    "tab_rename": "allowed",
    "tab_new": "allowed",
    "approval_inbox": "allowed",
    "preview": "allowed",
    "fork": "allowed",
    "master": "allowed",
    "fork_child": "allowed",
    "close": "allowed",
}
