from __future__ import annotations

VALUE_KEYWORDS_DATA: dict[str, dict[str, str]] = {
    "exec_command": {
        "cmd": "cmd",
        "workdir": "workdir",
        "shell": "shell",
        "login": "login",
        "yield-time-ms": "yield-time-ms",
        "timeout-ms": "timeout-ms",
        "max-output-tokens": "max-output-tokens",
        "sandbox-permissions": "sandbox-permissions",
        "justification": "justification",
        "prefix-rule": "prefix-rule",
        "additional-permissions-json": "additional-permissions-json",
    },
    "write_stdin": {
        "yield-time-ms": "yield-time-ms",
        "max-output-tokens": "max-output-tokens",
    },
    "connect": {
        "provider": "provider",
        "model": "model",
        "base-url": "base-url",
        "auth-mode": "auth-mode",
        "api-key-env": "api-key-env",
        "write": "write",
    },
    "setup": {
        "provider": "provider",
        "api-key": "api-key",
        "model": "model",
        "base-url": "base-url",
        "write": "write",
    },
    "auth": {
        "provider": "provider",
        "mode": "mode",
        "auth-code": "auth-code",
        "state": "state",
        "token-ref": "token-ref",
        "callback-timeout-seconds": "callback-timeout-seconds",
        "daemon": "daemon",
        "interval-seconds": "interval-seconds",
        "refresh-window-seconds": "refresh-window-seconds",
    },
    "provider": {"write": "write"},
    "model": {"reasoning-effort": "reasoning-effort", "write": "write"},
    "codex_threads": {"limit": "limit"},
    "codex_rollback": {"turns": "turns", "num-turns": "num-turns"},
    "threads": {"limit": "limit"},
    "mcp_auth": {"headers-json": "headers-json"},
    "mcp_auth_callback": {"token": "token", "callback-json": "callback-json"},
    "orchestrate_continue": {"max-passes": "max-passes", "dispatch-ready": "dispatch-ready"},
    "workflows": {"limit": "limit"},
    "background_tasks": {"limit": "limit"},
    "background_worker_start": {
        "max-jobs": "max-jobs",
        "poll-interval": "poll-interval",
        "stale-after-seconds": "stale-after-seconds",
    },
    "background_worker_run_once": {
        "max-jobs": "max-jobs",
        "stale-after-seconds": "stale-after-seconds",
    },
    "background_benchmark": {"timeout-seconds": "timeout-seconds"},
    "background_smoke": {"timeout-seconds": "timeout-seconds"},
    "background_teammate": {
        "provider": "provider",
        "model": "model",
        "reasoning-effort": "reasoning-effort",
        "cwd": "cwd",
        "approval-policy": "approval-policy",
        "sandbox-mode": "sandbox-mode",
        "allowed-paths": "allowed-paths",
        "blocked-paths": "blocked-paths",
        "timeout-seconds": "timeout-seconds",
    },
    "memory": {
        "limit": "limit",
        "status": "status",
        "scope": "scope",
        "type": "type",
    },
    "model-route": {
        "provider": "provider",
        "reasoning-effort": "reasoning-effort",
        "timeout": "timeout",
    },
    "model_route": {
        "provider": "provider",
        "reasoning-effort": "reasoning-effort",
        "timeout": "timeout",
    },
    "delegate-model": {
        "provider": "provider",
        "reasoning-effort": "reasoning-effort",
        "timeout": "timeout",
    },
    "delegate_model": {
        "provider": "provider",
        "reasoning-effort": "reasoning-effort",
        "timeout": "timeout",
    },
    "runtime_config": {
        "permission-mode": "permission-mode",
        "approval-policy": "approval-policy",
        "sandbox-mode": "sandbox-mode",
        "web-search-mode": "web-search-mode",
        "network-access": "network-access",
    },
    "plugin_install": {"scope": "scope"},
    "plugin_marketplace": {"path": "path", "scope": "scope"},
    "wait_agent": {
        "timeout-ms": "timeout-ms",
        "reason": "reason",
        "wait-required": "wait-required",
    },
    "agent_workflow": {"steps": "steps", "checkpoints": "checkpoints"},
    "recover_agent": {"action": "action", "step-id": "step-id"},
    "approvals": {"status": "status", "limit": "limit"},
    "approve": {"mode": "mode", "note": "note"},
    "reject": {"mode": "mode", "note": "note"},
    "glob_files": {"path": "path", "limit": "limit"},
    "grep_files": {
        "include": "include",
        "path": "path",
        "limit": "limit",
        "output-mode": "output-mode",
        "type": "type",
        "after": "after",
        "after-context": "after-context",
        "before": "before",
        "before-context": "before-context",
        "context": "context",
        "offset": "offset",
    },
    "read_file": {"offset": "offset", "limit": "limit"},
    "list_dir": {"offset": "offset", "limit": "limit", "depth": "depth"},
    "file_list": {"limit": "limit"},
    "file_search": {"path": "path", "limit": "limit"},
    "file_read": {"offset": "offset", "limit": "limit"},
    "web_search": {
        "limit": "limit",
        "domains": "domains",
        "recency-days": "recency-days",
        "market": "market",
        "blocked-domains": "blocked-domains",
    },
    "web_fetch": {"max-chars": "max-chars"},
    "browser": {
        "profile": "profile",
        "transport": "transport",
        "tab": "tab",
        "url": "url",
        "path": "path",
        "ref": "ref",
        "line": "line",
        "id": "id",
        "level": "level",
        "storage-kind": "storage-kind",
        "start-ref": "start-ref",
        "end-ref": "end-ref",
        "kind": "kind",
        "text": "text",
        "fn": "fn",
        "key": "key",
        "cookies-json": "cookies-json",
        "items-json": "items-json",
        "domain": "domain",
        "cookie-path": "cookie-path",
        "same-site": "same-site",
        "expires": "expires",
        "values": "values",
        "fields-json": "fields-json",
        "width": "width",
        "height": "height",
        "paths": "paths",
        "input-ref": "input-ref",
        "prompt-text": "prompt-text",
        "time-ms": "time-ms",
        "method": "method",
        "outcome": "outcome",
    },
    "open": {"line": "line"},
    "mcp": {
        "server": "server",
        "server-name": "server-name",
        "token": "token",
        "headers-json": "headers-json",
        "callback-json": "callback-json",
        "request-id": "request-id",
        "approved": "approved",
        "reason": "reason",
    },
    "list_mcp_resources": {"server-name": "server-name"},
    "read_mcp_resource": {"server-name": "server-name", "uri": "uri"},
    "mcp_resource": {"server": "server", "server-name": "server-name", "uri": "uri"},
    "mcp_tool_call": {"projected-name": "projected-name", "arguments-json": "arguments-json"},
    "policy_doc_import": {
        "path": "path",
        "library-root": "library-root",
        "data-root": "data-root",
    },
    "policy_doc_list": {
        "limit": "limit",
        "library-root": "library-root",
        "data-root": "data-root",
    },
    "policy_doc_search": {
        "query": "query",
        "limit": "limit",
        "library-root": "library-root",
        "data-root": "data-root",
    },
    "policy_doc_read": {
        "doc-id": "doc-id",
        "path": "path",
        "max-chars": "max-chars",
        "library-root": "library-root",
        "data-root": "data-root",
    },
    "github_issue_create": {
        "repo": "repo",
        "title": "title",
        "body": "body",
        "token-env": "token-env",
        "api-base-url": "api-base-url",
        "correlation-id": "correlation-id",
    },
    "github_issue_comment": {
        "repo": "repo",
        "issue-number": "issue-number",
        "body": "body",
        "token-env": "token-env",
        "api-base-url": "api-base-url",
        "correlation-id": "correlation-id",
    },
    "github_issue_add_labels": {
        "repo": "repo",
        "issue-number": "issue-number",
        "labels": "labels",
        "token-env": "token-env",
        "api-base-url": "api-base-url",
        "correlation-id": "correlation-id",
    },
    "github_issue_close": {
        "repo": "repo",
        "issue-number": "issue-number",
        "token-env": "token-env",
        "api-base-url": "api-base-url",
        "correlation-id": "correlation-id",
    },
    "github_workflow_dispatch": {
        "repo": "repo",
        "workflow-id": "workflow-id",
        "ref": "ref",
        "inputs-json": "inputs-json",
        "token-env": "token-env",
        "api-base-url": "api-base-url",
        "correlation-id": "correlation-id",
    },
    "github_approval_list": {"status": "status"},
    "github_approval_approve": {
        "approval-id": "approval-id",
        "decided-by": "decided-by",
        "decision-note": "decision-note",
    },
    "github_approval_reject": {
        "approval-id": "approval-id",
        "decided-by": "decided-by",
        "decision-note": "decision-note",
    },
}

BOOLEAN_KEYWORDS_DATA: dict[str, dict[str, str]] = {
    "exec_command": {"tty": "tty"},
    "providers": {"probe": "probe"},
    "connect": {"check": "check"},
    "setup": {"check": "check"},
    "auth": {
        "poll": "poll",
        "wait-callback": "wait-callback",
        "listen": "listen",
        "auto": "auto",
        "managed": "managed",
    },
    "memory": {"from-last-turn": "from-last-turn"},
    "model-route": {"clear": "clear"},
    "model_route": {"clear": "clear"},
    "delegate-model": {"clear": "clear"},
    "delegate_model": {"clear": "clear"},
    "models": {
        "include-hidden": "include-hidden",
        "hidden": "hidden",
        "all": "all",
        "refresh": "refresh",
        "force-refresh": "force-refresh",
    },
    "provider": {"verbose": "verbose", "probe": "probe"},
    "init": {"refresh": "refresh", "yes": "yes"},
    "background_worker_stop": {"force": "force"},
    "plugin_disable": {"all": "all"},
    "plugin_install": {"replace": "replace"},
    "plugin_marketplace": {"replace": "replace"},
    "approve": {"no-resume": "no-resume", "resume-only": "resume-only"},
    "reject": {"no-resume": "no-resume", "resume-only": "resume-only"},
    "send_input": {"interrupt": "interrupt"},
    "browser": {
        "http-only": "http-only",
        "secure": "secure",
        "accept": "accept",
        "dismiss": "dismiss",
    },
    "policy_doc_import": {"no-recursive": "no-recursive"},
    "grep_files": {
        "case-insensitive": "case-insensitive",
        "ignore-case": "ignore-case",
        "line-numbers": "line-numbers",
        "line-number": "line-number",
        "multiline": "multiline",
    },
}
