from __future__ import annotations

from cli.agent_cli.tools_core import (
    tool_registry_method_bindings_file_query_helpers_runtime,
    tool_registry_method_bindings_file_read_helpers_runtime,
)

glob_files = tool_registry_method_bindings_file_query_helpers_runtime.glob_files
glob_files_result = tool_registry_method_bindings_file_query_helpers_runtime.glob_files_result
grep_files = tool_registry_method_bindings_file_query_helpers_runtime.grep_files
grep_files_result = tool_registry_method_bindings_file_query_helpers_runtime.grep_files_result
list_dir = tool_registry_method_bindings_file_query_helpers_runtime.list_dir
list_dir_result = tool_registry_method_bindings_file_query_helpers_runtime.list_dir_result
file_list = tool_registry_method_bindings_file_query_helpers_runtime.file_list
file_list_result = tool_registry_method_bindings_file_query_helpers_runtime.file_list_result
file_search = tool_registry_method_bindings_file_query_helpers_runtime.file_search
file_search_result = tool_registry_method_bindings_file_query_helpers_runtime.file_search_result
read_file = tool_registry_method_bindings_file_read_helpers_runtime.read_file
read_file_result = tool_registry_method_bindings_file_read_helpers_runtime.read_file_result
file_read = tool_registry_method_bindings_file_read_helpers_runtime.file_read
file_read_result = tool_registry_method_bindings_file_read_helpers_runtime.file_read_result
_normalize_workspace_file_path = tool_registry_method_bindings_file_read_helpers_runtime._normalize_workspace_file_path
_remember_full_file_read = tool_registry_method_bindings_file_read_helpers_runtime._remember_full_file_read


FILE_METHOD_BINDINGS = (
    *tool_registry_method_bindings_file_query_helpers_runtime.FILE_QUERY_METHOD_BINDINGS,
    *tool_registry_method_bindings_file_read_helpers_runtime.FILE_READ_METHOD_BINDINGS,
)
