from __future__ import annotations

from cli.agent_cli.ui import status_controller_operator_evidence_helpers_runtime as _evidence_helpers
from cli.agent_cli.ui import status_controller_operator_projection_helpers_runtime as _projection_helpers
from cli.agent_cli.ui import status_controller_operator_text_helpers_runtime as _text_helpers


OPERATOR_STATUS_KEYS = _projection_helpers.OPERATOR_STATUS_KEYS
OPERATOR_HINT_KEYS = _projection_helpers.OPERATOR_HINT_KEYS
OPERATOR_EVIDENCE_KEYS = _projection_helpers.OPERATOR_EVIDENCE_KEYS
OPERATOR_PAYLOAD_KEYS = _projection_helpers.OPERATOR_PAYLOAD_KEYS
OPERATOR_COMMANDS = _text_helpers.OPERATOR_COMMANDS
OPERATOR_AGGREGATE_COMMANDS = _text_helpers.OPERATOR_AGGREGATE_COMMANDS
OPERATOR_TEXT_COMMANDS = _text_helpers.OPERATOR_TEXT_COMMANDS

_OPERATOR_QUEUED_STATES = _projection_helpers._OPERATOR_QUEUED_STATES
_OPERATOR_RUNNING_STATES = _projection_helpers._OPERATOR_RUNNING_STATES
_OPERATOR_RETURNED_COMPLETION_STATES = _projection_helpers._OPERATOR_RETURNED_COMPLETION_STATES
_OPERATOR_EVIDENCE_STATE_KEYS = _projection_helpers._OPERATOR_EVIDENCE_STATE_KEYS
_OPERATOR_EVIDENCE_SUBJECT_KEYS = _projection_helpers._OPERATOR_EVIDENCE_SUBJECT_KEYS
_OPERATOR_ARTIFACT_STATUS_KEYS = _projection_helpers._OPERATOR_ARTIFACT_STATUS_KEYS
_ELLIPSIS = _text_helpers._ELLIPSIS

status_text = _projection_helpers.status_text
boolish_status = _projection_helpers.boolish_status
normalized_status = _projection_helpers.normalized_status
operator_primary_state = _projection_helpers.operator_primary_state
merged_operator_key_values = _projection_helpers.merged_operator_key_values
operator_primary_state_from_mapping = _projection_helpers.operator_primary_state_from_mapping
operator_review_state = _projection_helpers.operator_review_state
operator_review_state_from_mapping = _projection_helpers.operator_review_state_from_mapping
operator_review_evidence_state = _projection_helpers.operator_review_evidence_state
operator_review_evidence_state_from_mapping = _projection_helpers.operator_review_evidence_state_from_mapping
operator_evidence_snapshot = _evidence_helpers.operator_evidence_snapshot
operator_evidence_from_status_sources = _evidence_helpers.operator_evidence_from_status_sources
operator_status_from_mapping = _evidence_helpers.operator_status_from_mapping
operator_payload_contains_status = _evidence_helpers.operator_payload_contains_status
operator_command_name = _text_helpers.operator_command_name
key_value_lines = _text_helpers.key_value_lines
operator_status_from_text = _text_helpers.operator_status_from_text
normalized_count = _projection_helpers.normalized_count
policy_entries = _text_helpers.policy_entries
policy_surface_hint = _text_helpers.policy_surface_hint
tool_label = _text_helpers.tool_label
